spring:
  application:
    name: authentication-service
    datasource:
        url: jdbc:postgresql://auth_db:5432/auth_db
        username: oliverdev
        password: Senha123$
        driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true

server:
    port: 8081
    servlet:
        context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:-3600000} # 1 hour
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:-604800000} # 7 days