spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080

server:
  port: 8080

auth:
  jwt:
    secret: secret-key
    expiration: 86400 # 24 horas